return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    opts = {
      -- flavour = "auto",
      -- configuration options...
      integrations = {
        blink_cmp = true,
        indent_blankline = {
          enabled = true,
          scope_color = "lavender", -- catppuccin color (eg. `lavender`) Default: text
          colored_indent_levels = false,
        },
        noice = true,
        snacks = {
          enabled = true,
          indent_scope_color = "lavender", -- catppuccin color (eg. `lavender`) Default: text
        },
      },
      transparent_background = false,
      background = {
        dark = "mocha",
        light = "latte",
      },
      color_overrides = {
        mocha = {
          rosewater = "#ffb59d",
          -- flamingo = "#ffb59d",
          pink = "#ffb2b9",
          mauve = "#e6b6f1",
          red = "#ffb2b9",
          maroon = "#ffb2b9",
          peach = "#ffb59d",
          yellow = "#f5bd6f",
          green = "#e2c28c",
          teal = "#b1d18a",
          sky = "#ffb3af",
          sapphire = "#b8c4ff",
          blue = "#ffb3af",
          lavender = "#ffb3af",
          text = "#f0dedd",
          subtext1 = "#cccccc",
          subtext0 = "#bbbbbb",
          overlay2 = "#aaaaaa",
          overlay1 = "#999999",
          overlay0 = "#888888",
          surface2 = "#777777",
          surface1 = "#666666",
          surface0 = "#555555",
          -- surface0 = "#e7bdba",
          base = "#1a1111",
          mantle = "#1a1111",
          crust = "#1a1111",
        },
        latte = {
          rosewater = "#ffb59d",
          flamingo = "#ffb59d",
          pink = "#ffb2b9",
          mauve = "#e6b6f1",
          red = "#ffb2b9",
          maroon = "#ffb2b9",
          peach = "#ffb59d",
          yellow = "#f5bd6f",
          green = "#e2c28c",
          teal = "#b1d18a",
          sky = "#ffb3af",
          sapphire = "#b8c4ff",
          blue = "#ffb3af",
          lavender = "#ffb3af",
          text = "#f0dedd",
          -- 明亮配色
          subtext1 = "#444444",
          subtext0 = "#555555",
          overlay2 = "#666666",
          overlay1 = "#777777",
          overlay0 = "#888888",
          surface2 = "#999999",
          surface1 = "#aaaaaa",
          surface0 = "#bbbbbb",
          base = "#1a1111",
          mantle = "#1a1111",
          crust = "#1a1111",
        },
      },
    },
  },
}
